Announcements
socketkit/javascript-sdk pull request #2
Opened 2018-05-05 17:26 UTC by batilc1

2018-05-06 17:33 UTC, anonrig requested changes

2018-05-06 17:33 UTC, anonrig commented on src/chat.js
> +  async setParticipantMessageRight(roomId, targetUniqueClientKey, canPostMessage) {
Genel olarak bu SDK'da yaptigimiz en buyuk hata bence ayri ayri parametre olarak bu inputlari almak. SDK'yi okumadigimda hangisinde ne oldugunu anlamak zor oluyor, tek bir parametre ile

{roomId, targetUniqueClientKey, canPostMessage} seklinde duzeltebilir miyiz burayi?

2018-05-06 17:33 UTC, anonrig commented on src/chat.js
> +    return this.client.send(Chat.InternalEvent.SET_PARTICIPANT_MESSAGE_RIGHT, {roomId, targetUniqueClientKey, canPostMessage});
cok uzun line :( new line'i sevelim...

2018-05-06 17:33 UTC, anonrig commented on src/chat.js
> +  async createRoom({title, isPrivate = false, announcementOnly: restricted = false, properties = {}} = {}) {
Yukardaki ornekte ilk parametre title'ken, burda ilk parametre bir obje. Obje olarak yapmayi daha cok sevdim ama yukardaki ornegi de duzeltebilir misin. Line 309

2018-05-06 17:33 UTC, anonrig commented on src/chat.js
> +  SET_PARTICIPANT_MESSAGE_RIGHT: 'set_participant_message_right',
`SET_PARTICIPANT_PERMISSION` ? :/

2018-05-06 18:11 UTC, batilc1 commented on src/chat.js
> +  async setParticipantMessageRight(roomId, targetUniqueClientKey, canPostMessage) {
katiliyorum, ben full named parameter'dan yanayim. mevcut convention'i takip ettim sadece. ayiralim

2018-05-06 18:23 UTC, anonrig commented on src/chat.js
> +  async setParticipantMessageRight(roomId, targetUniqueClientKey, canPostMessage) {
👍

2018-05-06 18:42 UTC, batilc1 commented on src/chat.js
> +  SET_PARTICIPANT_MESSAGE_RIGHT: 'set_participant_message_right',
core'daki pr'da kararlastiracagimiz isimle ayni yapariz

2018-05-08 14:11 UTC, anonrig reviewed
Parametreleri {} olarak almaya karar verdikten sonra JSDoc'lar eskisi gibi kalmis. Onlari duzeltip bir de, default valuelari da JSDoc'a aktardiktan sonra `npm run build:docs` calistirip documentation'i da guncelleyebilirsen cok sevinirim 👍

2018-05-08 14:11 UTC, anonrig commented on src/chat.js
> +   * @param {!Number} roomId Room id
```
@param {!Object} payload
@param {!Number} payload.roomId Room id.
```

Seklinde olmasi gerekiyor JSDoc'un

2018-05-08 14:11 UTC, anonrig commented on src/chat.js
> +   * @param {!Number} targetUniqueClientKey Target client id
JSDOC eski parametrelerden kalmis. payload.targetUniqueClientKey olmasi lazim

2018-05-08 16:08 UTC, anonrig approved these changes

2018-05-08 16:08 UTC, merged